# Generated by Django 2.0 on 2018-01-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbevents', '0002_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='observer',
            name='session',
            field=models.CharField(default='mokoko', max_length=256),
            preserve_default=False,
        ),
    ]
